name: verigrade
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  camera: 0.10.5+9          # <- pinned for compileSdk 35
  cupertino_icons: ^1.0.8
  provider: ^6.1.5
  image_picker: ^1.2.0
  image: ^4.5.4
  google_fonts: ^6.2.1
  path_provider: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4
  flutter_native_splash: ^2.4.6

flutter_native_splash:
  color: "#000000"
  image: assets/logo_splash.png
  android_12:
    color: "#000000"
    image: assets/logo_splash.png

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo_launcher.png
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: assets/logo_launcher.png

flutter:
  uses-material-design: true
  assets:
    - assets/logo_splash.png
    - assets/logo_launcher.png      # optional, but handy
    - assets/fonts/BebasNeue-Regular.ttf
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
